### ISSUE TITLE
Banner image size

### ISSUE THREAD

**Issue by shubhamagarwal92** [jponttuset/jponttuset.github.io#4]
Hi Jordi, 

Thank you for providing the theme and open-sourcing the code. Really helpful!

- Is there a way to define the height of the banner? I wanted to use one of my [clicks](https://github.com/shubhamagarwal92/shubhamagarwal92.github.io/blob/master/images/hawaii.jpg), however, it is taking half of the page (unlike the trees photo you used)
- or is there any specific aspect ratio (or height width) to be maintained in the photo we want as a banner? 

Thanks for the help!

**Comment by jponttuset** [comment]
Hi @shubhamagarwal92,

The behavior of the header should be defined in the CSS of the minimal mistakes template, I never tweaked it, so I cannot point you exactly to it. I do remember cropping the image to be very wide.

Sorry I do not have a more useful answer.

PS: Thanks for the mention in your repo, and glad it helped you.

**Comment by shubhamagarwal92** [comment]
Hi @jponttuset 

Thanks for your response. No worries. I will try to play around with the CSS / image size. 

Closing the issue now.

**Comment by shubhamagarwal92** [comment]
btw @jponttuset 
I hope you don't mind me using your images till the time I figure this out? Would it be okay?

**Comment by jponttuset** [comment]
No problem :)
